services:
  paper-analysis:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      VENV: /opt/fibromyalgia-ema-venv
    volumes:
      - ../:/workspace
    working_dir: /workspace
    command: ["make", "check"]
